-- 0017_report_generations_and_sonnet_direct.sql
--
-- Phase 7.4 calibration harness — Column C (ANÁLISE DIRETA SONNET) +
-- per-method generation instrumentation.
--
-- Two strictly-additive changes shipped together (one feature):
--
--   1. readings.*_sonnet_direct columns — mirror the 0016 *_sam pattern.
--      A third parallel report (Sonnet looking at the 6 photos directly,
--      NO pipeline features, NO RAG) lives in dedicated nullable columns so
--      production `vision_features` / `report_generated` and the SAM columns
--      are never touched. NULL = no Sonnet-direct run yet.
--
--   2. report_generations — instrumentation table. Every report generation
--      (vigente | sam | sonnet_direct) logs latency / cost / tokens / model
--      so the founder can compare "how much value comes from the extracted
--      features vs. what Sonnet sees directly" AND the $ economics of each.
--
-- Strictly additive. No data migration, no default on the new readings
-- columns, no backfill. Existing rows and all current code paths are
-- unaffected (every read of the new columns must treat NULL = "no run yet";
-- every report_generations insert is best-effort and never blocks a
-- generation).
--
-- Division of labor: Claude authored this migration; the founder applies it
-- to the production database (supabase db push / dashboard) — same pattern
-- as migration 0016 and the Modal deploy. The comparison page and the
-- sonnet-direct route both degrade gracefully (actionable "migration 0017
-- pendente" notice) until it is applied.

-- ── 1. readings: parallel Sonnet-direct columns (mirror 0016 *_sam) ─────────
alter table public.readings
  add column if not exists report_generated_sonnet_direct      jsonb,
  add column if not exists report_generated_sonnet_direct_at   timestamptz,
  add column if not exists sonnet_direct_run_metadata           jsonb;

comment on column public.readings.report_generated_sonnet_direct is
  'Phase 7.4 Column C: report (same ReportJsonb shape as report_generated) generated by Sonnet looking at the 6 photos directly — NO pipeline features, NO RAG. NULL = no run. Never overwrites report_generated / _sam.';
comment on column public.readings.report_generated_sonnet_direct_at is
  'Phase 7.4 Column C: timestamp of the last Sonnet-direct report generation.';
comment on column public.readings.sonnet_direct_run_metadata is
  'Phase 7.4 Column C: provenance (model_version=sonnet_direct_0.1.0, sonnet model, n_images, image_px, triggered_by, latency/cost/tokens, audit anchor rate, error_summary).';

-- ── 2. report_generations: per-method instrumentation ──────────────────────
create table if not exists public.report_generations (
  id                       uuid primary key default gen_random_uuid(),
  reading_id               uuid not null,
  method                   text not null check (method in ('vigente', 'sam', 'sonnet_direct')),
  generated_at             timestamptz not null default now(),
  latency_ms               integer,
  cost_usd                 numeric(10, 5),
  tokens_in                integer,
  tokens_out               integer,
  model_version            text,
  -- 07.4-36 founder amendment — production analytics surface (2-3 week horizon):
  prompt_version           text,
  canonical_fallback_count integer,
  audit_summary            jsonb,
  regeneration_count       integer,
  client_id                uuid,
  bbox_cost_usd            numeric(10, 5),
  bbox_latency_ms          integer,
  created_at               timestamptz not null default now()
);

-- Idempotent guard: if a partial/earlier 0017 was ever applied, `create table
-- if not exists` is a no-op and would NOT add the amendment columns — so add
-- them explicitly too. Safe on a fresh table (already present → no-op).
alter table public.report_generations
  add column if not exists prompt_version           text,
  add column if not exists canonical_fallback_count integer,
  add column if not exists audit_summary            jsonb,
  add column if not exists regeneration_count       integer,
  add column if not exists client_id                uuid,
  add column if not exists bbox_cost_usd            numeric(10, 5),
  add column if not exists bbox_latency_ms          integer;

comment on table public.report_generations is
  'Phase 7.4 calibration instrumentation: one row per report generation across the 3 comparison methods (vigente | sam | sonnet_direct). Best-effort insert — never blocks a generation. No FK on reading_id (decoupled from readings lifecycle / migration order).';
comment on column public.report_generations.cost_usd is
  'Cost of the REPORT generation Anthropic call only (Sonnet writing the 15 sections). Excludes the canonicalization bbox call — see bbox_cost_usd.';
comment on column public.report_generations.model_version is
  'Anthropic MODEL id (e.g. claude-sonnet-…). NOT the prompt version — see prompt_version.';
comment on column public.report_generations.prompt_version is
  '07.4-36: short sha256 of the effective system.md content at generation time (getSystemPromptVersion). Lets quality/cost shifts be attributed to prompt iteration vs model change.';
comment on column public.report_generations.canonical_fallback_count is
  '07.4-36: # of the 6 photos that fell back to the raw uncentered frame (canonicalization trust-gate) for THIS generation. Per-generation snapshot (readings.audit_metadata is overwritten each regen).';
comment on column public.report_generations.audit_summary is
  '07.4-36: the AuditMetadata for this generation (low_anchor_rate, anchor_rate_pct, forbidden_vocab[], audited_at). Per-generation snapshot.';
comment on column public.report_generations.regeneration_count is
  '07.4-36: readings.regeneration_count AFTER this generation (1 = first generation, 2 = first regen, …). Authoritative even if a best-effort insert is ever lost.';
comment on column public.report_generations.client_id is
  '07.4-36: denormalized readings.client_id (no FK — mirrors the reading_id decoupling). Survives reading deletion; avoids a join for per-client cost rollups.';
comment on column public.report_generations.bbox_cost_usd is
  '07.4-36: cost of the SEPARATE canonicalization (Sonnet-bbox) Anthropic call for this reading, read from readings.canonical_metadata.cost_usd. Total reading $ = cost_usd + bbox_cost_usd.';
comment on column public.report_generations.bbox_latency_ms is
  '07.4-36: wall-clock latency of the canonicalization batch (6 parallel bbox calls), from readings.canonical_metadata.bbox_latency_ms.';

create index if not exists report_generations_reading_id_idx
  on public.report_generations (reading_id);
create index if not exists report_generations_method_idx
  on public.report_generations (method);

-- RLS — founder-only read (mirror calibration_* policy from 0011: read the
-- email straight from the JWT, never touch auth.users). Service-role inserts
-- from the generation routes bypass RLS. Defense-in-depth: middleware.ts +
-- app/admin/layout.tsx + isFounderEmail already gate /admin; this is the
-- 4th layer.
alter table public.report_generations enable row level security;
drop policy if exists "founder_full_access" on public.report_generations;
create policy "founder_full_access"
  on public.report_generations
  for all
  to authenticated
  using ((auth.jwt() ->> 'email') = 'rhelton@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'rhelton@gmail.com');
